### ISSUE TITLE
DEMO运行报错

### ISSUE THREAD

**Issue by isensen** [ldcf4/UnityInfinityRandomTerrainDemo#1]
我使用的版本是5.3.5.f1 ， 项目打开报错，导致场景无法打开， 不知道作者场景里如何使用各个组件 ，所以无法正确运行，作者是否可以说明一下使用方法

**Comment by ldcf4** [comment]
我用的是5.5，不过5.3理论上应该没有问题。项目里只有一个场景，直接打开场景就可以运行了啊。组件配置文字说不清楚，我在论坛上补充了，你去看一下吧。
http://www.manew.com/forum.php?mod=viewthread&tid=102355&page=1&extra=#pid1382183

**Comment by isensen** [comment]
恩，我自己之前看了看脚本，配了一下，和你贴子里说的差不多， 运行时会报几个错误， 不知道能否加QQ请教一下
